force-app/main/default/objects/Account/fields/SOSAO__SecondAccountOwner__c.field-meta.xml
<CustomField>
    <fullName>SOSAO__SecondAccountOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the 2nd Account Owner Field i.e., NOT to be added to the Page Layout</description>
    <inlineHelpText>Syncs to Gainsight.</inlineHelpText>
    <label>SecondAccountOwner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <label>Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abu Dhabi</fullName>
            </value>
            <value>
                <fullName>Admiralty Islands</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Ajman</fullName>
            </value>
            <value>
                <fullName>Al Ain</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Ascension Island</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partners_Configuration__c/Partners_Configuration__c.object-meta.xml
<CustomObject>
    <label>Partner Configuration</label>
    <nameField>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partners_Configuration__c/fields/Partner_Email__c.field-meta.xml
<CustomField>
    <fullName>Partner_Email__c</fullName>
    <inlineHelpText>Enter partner&#39;s emails with (;) separated</inlineHelpText>
    <label>Partner Email</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/EmailToPartner.cls
/*
Helper class for AppCenterController
Code coverage included in AppCenterControllerTest class
*/
public class EmailToPartner{
    
    public void sendEmail(String taskId,String partnerName,string accId)
    {   
        List<String> toAddressList = new List<String>();  
        List<String> ccAddressList = new List<String>();
        Account acc;  
        for(Partners_Configuration__c p: [Select  Partner_Email__c from Partners_Configuration__c where Name =:partnerName])
        {
            if(p.Partner_Email__c != null)
            {
                toAddressList = p.Partner_Email__c.split(';');
            }    
        }
        //Get account details
        if(accId != null)
        {
            for(Account accObj : [Select id,Owner.Email, SOSAO__SecondAccountOwner__c,SOSAO__SecondAccountOwner__r.Email from Account where id =:accId])
            {
                if(accObj.Owner.Email != null)
                ccAddressList.add(accObj.Owner.Email);
                if(accObj.SOSAO__SecondAccountOwner__c  != null && accObj.SOSAO__SecondAccountOwner__r.Email != null)
                ccAddressList.add(accObj.SOSAO__SecondAccountOwner__r.Email);
                
                system.debug('***JN***'+ccAddressList);
            }    
        }
        system.debug('***JN 1***'+ccAddressList);
        ccAddressList.add(UserInfo.getUserEmail());
        // Create Contact
        Contact con = new Contact();
        con.FirstName = 'Test';
        con.LastName = 'Contact';
        con.Billing_Country__c = 'USA';
        if(toAddressList != null && toAddressList.size()> 0)
        con.Email = toAddressList[0];
        else
        con.Email = 'jagmohan.negi85@gmail.com';
        con.RecordTypeId=Schema.SObjectType.Contact.getRecordTypeInfosByName().get('GlobalExpense Service Profile').getRecordTypeId();
       
        insert con;
        // Create Email and Send
        Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();
        msg.setTemplateId([select id,name from EmailTemplate where DeveloperName='App_Center_Referral_Task_Email_VF'].id);
        msg.setToAddresses(toAddressList);
        if(ccAddressList != null)
        msg.setCcAddresses(ccAddressList);
        msg.setTargetObjectId(con.Id);
        msg.setWhatId(taskId);
        msg.setSaveAsActivity(false);
        if(!Test.isRunningTest())
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { msg });
        delete con;

    }
 }