force-app/main/default/objects/Contact/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <label>Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abu Dhabi</fullName>
            </value>
            <value>
                <fullName>Admiralty Islands</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Ajman</fullName>
            </value>
            <value>
                <fullName>Al Ain</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Ascension Island</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partners_Configuration__c/Partners_Configuration__c.object-meta.xml
<CustomObject>
    <label>Partner Configuration</label>
    <nameField>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partners_Configuration__c/fields/Partner_Category__c.field-meta.xml
<CustomField>
    <fullName>Partner_Category__c</fullName>
    <label>Partner Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Air &amp; Hotel</fullName>
            </value>
            <value>
                <fullName>Cars &amp; Trains</fullName>
            </value>
            <value>
                <fullName>Compliance &amp; Risk</fullName>
            </value>
            <value>
                <fullName>Finance &amp; HR</fullName>
            </value>
            <value>
                <fullName>Life Sciences</fullName>
            </value>
            <value>
                <fullName>IT Solutions</fullName>
            </value>
            <value>
                <fullName>Other Expenses</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partners_Configuration__c/fields/Partner_Email__c.field-meta.xml
<CustomField>
    <fullName>Partner_Email__c</fullName>
    <inlineHelpText>Enter partner&#39;s emails with (;) separated</inlineHelpText>
    <label>Partner Email</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AppCenterControllerTest.cls
@isTest
public class AppCenterControllerTest {

    public static testMethod void testMyController() {
    Partners_Configuration__c pconfig = new Partners_Configuration__c();
    List<Selectoption> testSelectOption;
    PageReference pRefTest; 
    pconfig.Name='AppCenterTest';
   // pconfig.Partner_Category__c = 'IT Solutions';
    pconfig.Partner_Email__c = 'test@concur.com';
    insert pconfig;
    //Test Account
    Account acc = new Account(Name='Test Account');
    insert acc;
    Contact con = new Contact(LastName='lastname',accountid=acc.id, Billing_Country__c = 'USA');
    insert con;
    Task t = new Task(status='Completed',subject='Test subject',ActivityDate=System.today(),whatId = acc.id,whoid=con.id,ownerId=UserInfo.getUserId(),Priority='Normal');
    //insert t;
    
    
        PageReference pageRef = Page.AppCenterReferral;
        Test.setCurrentPage(pageRef);
      ApexPages.currentPage().getParameters().put('recId', acc.id);

        AppCenterController controller = new AppCenterController();
        controller.tsk = t;
     //   controller.selectedCategory ='IT Solutions';
        controller.selectedPartner =pconfig.Name;
      //  testSelectOption = controller.getCategories();
      //  controller.CategoryChanged();
        testSelectOption = controller.getPartners();
        pRefTest = controller.saveTask();
        pRefTest = controller.cancelTask();
        controller.ContactUpdated();
        
        controller.selectedCategory = null;
        pRefTest = controller.saveTask();
        controller.selectedCategory ='IT Solutions';
        controller.selectedPartner = null;
        pRefTest = controller.saveTask();
        
         ApexPages.currentPage().getParameters().put('recId', con.id);
         controller = new AppCenterController();
      
         
        
    }
}